In [ ]:
# !python -m venv sklearn-env
# sklearn-env\Scripts\activate  # activate
# pip install -U scikit-learn

Carregando o dataset

In [1]:
import pandas as pd

df = pd.read_csv("netflix_titles.csv")
df.head()
#por padrão, nos retorna as 5 primeiras linhas do dataset, mas podemos passar um parâmetro para retornar mais ou menos linhas. Ex: df.head(10) retorna as 10 primeiras linhas do dataset.

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [7]:
df.shape
# nos retorna o número de linhas e colunas do dataset.

(8807, 12)

In [4]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [8]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [9]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

# Declaração do problema que queremos solucionar: Dadas as informações de um conteúdo, prever se ele é um Movie ou TV Show.

y = aquilo que queremos prever → type
X = informações que vamos fornecer ao modelo

Para aprender, vamos ignorar duration (min x seasons) e usar release_year (numérica) e rating (categórica) para facilitar.

In [10]:
y = df["type"]                  # alvo
X = df[["release_year", "rating"]]   # features

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("netflix_titles.csv")

X = df[["release_year", "rating"]]
y = df["type"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
# test_size=0.2 significa que 20% dos dados serão destinados ao conjunto de teste. (80% treinamento)
# random_state=42 fixa a aleatoriedade da divisão. Sem isso, cada execução poderia separar os dados de maneira diferente. Com random_state=42, conseguimos reproduzir a mesma divisão.
# stratify=y mantém a mesma proporção das classes da variável alvo no conjunto de treino e teste, evitando que uma classe fique sub ou superrepresentada na divisão.